markdown: kramdown
permalink: /blog/:title/

exclude:
  - .vscode
  - node_modules
  - package.json
  - Gemfile
  - Gemfile.lock
  - package-lock.json
  - assets
  - css
  - js
  - pages
  - index.html

include:
  - _posts
  - _layouts

plugins:
  - jekyll-feed
  - jekyll-seo-tag